# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
#destination:      _gh_pages
host:             0.0.0.0
port:             4001
baseurl:          /docs/3.4
encoding: UTF-8

plugins:
  - jekyll-sitemap

# Custom vars
title: "GitHub pages experiments"
working_jekyll_version: "3.8.6"